FROM python:3.10

# LABEL org.opencontainers.image.authors="https://github.com/Vasyl-Hlushchenko"

WORKDIR /app

ENV POETRY_VIRTUALENVS_CREATE = False

RUN pip install poetry

COPY ["poetry.lock", "pyproject.toml", "/app/"]

RUN poetry install --no-ansi --no-interaction

COPY . /app

CMD ["python", "main.py"]

# ENTRYPOINT ["bot"]
