[tool.poetry]
name = "contactbook"
version = "1.0.0"
description = "\"\""
authors = ["Vasyl Hlushchenko"]
license = "\"\""
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
